//
// AbstractPageLinks.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AbstractPageLinks {

    /** Web UI link of the content. */
    public var webui: String?
    /** Edit UI link of the content. */
    public var editui: String?
    /** Web UI link of the content. */
    public var tinyui: String?

    public init(webui: String? = nil, editui: String? = nil, tinyui: String? = nil) {
        self.webui = webui
        self.editui = editui
        self.tinyui = tinyui
    }

    internal init(client: Components.Schemas.AbstractPageLinks?) {
        self.webui = client?.webui
        self.editui = client?.editui
        self.tinyui = client?.tinyui
    }
}
