//
// AccountType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The account type of the user. */
public enum AccountType: String, Codable {
    case atlassian = "atlassian"
    case app = "app"
    case customer = "customer"
    case unknown = "unknown"
    
    internal init(client: Components.Schemas.AccountType?) {
        switch client {
        case .atlassian: self = .atlassian
        case .app: self = .app
        case .customer: self = .customer
        case .unknown: self = .unknown
        case .none: self = .unknown
        }
    }
}
