//
// AccountStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The account status of the user. */
public enum AccountStatus: String, Codable {
    case active = "active"
    case inactive = "inactive"
    case closed = "closed"
    case unknown = "unknown"
    
    internal init(client: Components.Schemas.AccountStatus?) {
        switch client {
        case .active: self = .active
        case .inactive: self = .inactive
        case .closed: self = .closed
        case .unknown: self = .unknown
        case .none: self = .unknown
        }
    }
}
