//
// AttachmentSingleVersions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AttachmentSingleVersions {

    public var results: [Version]?
    public var meta: OptionalFieldMeta?
    public var links: OptionalFieldLinks?

    public init(results: [Version]? = nil, meta: OptionalFieldMeta? = nil, links: OptionalFieldLinks? = nil) {
        self.results = results
        self.meta = meta
        self.links = links
    }
    
    internal init(client: Components.Schemas.PageSingle.versionsPayload?) {
        self.results = client?.results?.map{ Version(client: $0) }
        self.meta = OptionalFieldMeta(client: client?.meta)
        self.links = OptionalFieldLinks(client: client?._links)
    }
}
