//
// AttachmentSingleOperations.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AttachmentSingleOperations {

    public var results: [Operation]?
    public var meta: OptionalFieldMeta?
    public var links: OptionalFieldLinks?

    public init(results: [Operation]? = nil, meta: OptionalFieldMeta? = nil, links: OptionalFieldLinks? = nil) {
        self.results = results
        self.meta = meta
        self.links = links
    }

    public enum CodingKeys: String, CodingKey {
        case links = "_links"
    }

    internal init(client: Components.Schemas.PageSingle.operationsPayload?) {
        self.results = client?.results?.map{ Operation(client: $0) }
        self.meta = OptionalFieldMeta(client: client?.meta)
        self.links = OptionalFieldLinks(client: client?._links)
    }
}
