//
// BlogPostSingleLikes.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BlogPostSingleLikes {

    public var results: [Like]?
    public var meta: OptionalFieldMeta?
    public var links: OptionalFieldLinks?

    public init(results: [Like]? = nil, meta: OptionalFieldMeta? = nil, links: OptionalFieldLinks? = nil) {
        self.results = results
        self.meta = meta
        self.links = links
    }

    internal init(client: Components.Schemas.PageSingle.likesPayload?) {
        self.results = client?.results?.map{ Like(client: $0) }
        self.meta = OptionalFieldMeta(client: client?.meta)
        self.links = OptionalFieldLinks(client: client?._links)
    }
}
