//
// BodySingle.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Contains fields for each representation type requested. */

public struct BodySingle: Codable {

    public var storage: BodyType?
    public var atlasDocFormat: BodyType?
    public var view: BodyType?

    public init(storage: BodyType? = nil, atlasDocFormat: BodyType? = nil, view: BodyType? = nil) {
        self.storage = storage
        self.atlasDocFormat = atlasDocFormat
        self.view = view
    }

    public enum CodingKeys: String, CodingKey { 
        case storage
        case atlasDocFormat = "atlas_doc_format"
        case view
    }
    
    internal init(client: Components.Schemas.BodySingle?) {
        self.storage = BodyType(client: client?.storage)
        self.atlasDocFormat = BodyType(client: client?.atlas_doc_format)
        self.view = BodyType(client: client?.view)
    }
}
