//
// BodyType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BodyType {

    /** Type of content representation used for the value field. */
    public var representation: String?
    /** Body of the content, in the format found in the representation field. */
    public var value: String?

    public init(representation: String? = nil, value: String? = nil) {
        self.representation = representation
        self.value = value
    }

    internal init(client: Components.Schemas.BodyType?) {
        self.representation = client?.representation
        self.value = client?.value
    }
}
