//
// ChildPage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChildPage {

    /** ID of the page. */
    public var id: String?
    public var status: OnlyArchivedAndCurrentContentStatus?
    /** Title of the page. */
    public var title: String?
    /** ID of the space the page is in. */
    public var spaceId: String?
    /** Position of child page within the given parent page tree. */
    public var childPosition: Int32?

    public init(id: String? = nil, status: OnlyArchivedAndCurrentContentStatus? = nil, title: String? = nil, spaceId: String? = nil, childPosition: Int32? = nil) {
        self.id = id
        self.status = status
        self.title = title
        self.spaceId = spaceId
        self.childPosition = childPosition
    }
    
    internal init(client: Components.Schemas.ChildPage?) {
        self.id = client?.id
        self.status = OnlyArchivedAndCurrentContentStatus(status: client?.status)
        self.title = client?.title
        self.spaceId = client?.spaceId
        self.childPosition = client?.childPosition
    }
}
