//
// ContentStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The status of the content. */
public enum ContentStatus: String, Codable {
    case current = "current"
    case draft = "draft"
    case archived = "archived"
    case historical = "historical"
    case trashed = "trashed"
    case deleted = "deleted"
    case any = "any"
    
    internal init(status: Components.Schemas.ContentStatus?) {
        switch status {
        case .current: self = .current
        case .archived: self = .archived
        case .deleted: self = .deleted
        case .draft: self = .draft
        case .historical: self = .historical
        case .trashed: self = .trashed
        case .none: self = .any
        case .any: self = .any
        }
    }
}
