//
// ContentStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The status of the content. */
public enum ContentStatus: String {
    case current = "current"
    case draft = "draft"
    case archived = "archived"
    case historical = "historical"
    case trashed = "trashed"
    case deleted = "deleted"
    
    internal init(status: Components.Schemas.ContentStatus?) {
        switch status {
        case .current: self = .current
        case .archived: self = .archived
        case .deleted: self = .deleted
        case .draft: self = .draft
        case .historical: self = .historical
        case .trashed: self = .trashed
        default : self = .current
        }
    }
    
    internal func toQuery() -> Operations.getPageById.Input.Query.statusPayloadPayload {
        switch self {
            
        case .current:
                .current
        case .draft:
                .draft
        case .archived:
                .archived
        case .historical:
                .historical
        case .trashed:
                .trashed
        case .deleted:
                .deleted
        }
    }
}
