//
// ContentProperty.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ContentProperty {

    /** ID of the property */
    public var id: String?
    /** Key of the property */
    public var key: String?
    /** Value of the property. Must be a valid JSON value. */
    public var value: Any?
    public var version: Version?

    public init(id: String? = nil, key: String? = nil, value: Any? = nil, version: Version? = nil) {
        self.id = id
        self.key = key
        self.value = value
        self.version = version
    }

    internal init(client: Components.Schemas.ContentProperty?) {
        self.id = client?.id
        self.key = client?.key
        self.version = Version(client: client?.version)
    }
}
