//
// Icon.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** This object represents an icon. If used as a profilePicture, this may be returned as null, depending on the user&#x27;s privacy setting. */

public struct Icon {

    public var path: String?
    public var isDefault: Bool?

    internal init(client: Components.Schemas.Icon?) {
        self.path = client?.path
        self.isDefault = client?.isDefault
    }
}
