//
// Like.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Like: Codable {

    /** Account ID. */
    public var accountId: String?

    public init(accountId: String? = nil) {
        self.accountId = accountId
    }

    internal init(client: Components.Schemas.Like?) {
        self.accountId = client?.accountId
    }
}
