//
// Operation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Operation {

    /** The type of operation. */
    public var operation: String?
    /** The type of entity the operation type targets. */
    public var targetType: String?

    public init(operation: String? = nil, targetType: String? = nil) {
        self.operation = operation
        self.targetType = targetType
    }


    internal init(client: Components.Schemas.Operation?) {
        self.operation = client?.operation
        self.targetType = client?.targetType
    }
}
