//
// OptionalFieldLinks.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OptionalFieldLinks: Codable {

    /** A relative URL that can be used to fetch results beyond what this include parameter retrieves. */
    public var _self: String?

    public init(_self: String? = nil) {
        self._self = _self
    }

    public enum CodingKeys: String, CodingKey { 
        case _self = "self"
    }

    internal init(client: Components.Schemas.OptionalFieldLinks?) {
        self._self = client?._self
    }
}
