//
// OptionalFieldMeta.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OptionalFieldMeta {

    /** Indicates if there are more available results that can be fetched. */
    public var hasMore: Bool?
    /** A token that can be used in the query parameter of the endpoint returned in the &#x60;links&#x60; property to retrieve the next set of results. */
    public var cursor: String?

    public init(hasMore: Bool? = nil, cursor: String? = nil) {
        self.hasMore = hasMore
        self.cursor = cursor
    }

    internal init(client: Components.Schemas.OptionalFieldMeta?) {
        self.hasMore = client?.hasMore
        self.cursor = client?.cursor
    }
}
