//
// ParentContentType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Content type of the parent, or null if there is no parent. */
public enum ParentContentType: String, Codable {
    case page = "page"
    case whiteboard = "whiteboard"
    case database = "database"
    case embed = "embed"
    case folder = "folder"
    case none = "none"
    
    internal init(type: Components.Schemas.ParentContentType?) {
        switch type {
        case .database: self = .database
        case .embed: self = .embed
        case .folder: self = .folder
        case .page: self = .page
        case .whiteboard: self = .whiteboard
        case .none: self = .none
        }
    }
}
