//
// User.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct User {

    /** Display name of the user. */
    public var displayName: String?
    /** Time zone of the user. Depending on the user&#x27;s privacy setting, this may return null. */
    public var timeZone: String?
    /** Space ID of the user&#x27;s personal space. Returns null, if no personal space for the user. */
    public var personalSpaceId: String?
    /** Whether the user is an external collaborator. */
    public var isExternalCollaborator: Bool?
    public var accountStatus: AccountStatus?
    /** Account ID of the user. */
    public var accountId: String?
    /** The email address of the user. Depending on the user&#x27;s privacy setting, this may return an empty string. */
    public var email: String?
    public var accountType: AccountType?
    /** Public name of the user. */
    public var publicName: String?
    public var profilePicture: Icon?

    internal init(client: Components.Schemas.User?) {
        self.displayName = client?.displayName
        self.timeZone = client?.timeZone
        self.personalSpaceId = client?.personalSpaceId
        self.isExternalCollaborator = client?.isExternalCollaborator
        self.accountStatus = AccountStatus(client: client?.accountStatus)
        self.accountId = client?.accountId
        self.email = client?.email
        self.accountType = AccountType(client: client?.accountType)
        self.publicName = client?.publicName
        self.profilePicture = Icon(client: client?.profilePicture)
    }

}
