//
// Ancestor.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Ancestor: Codable {

    /** ID of the ancestor */
    public var _id: String?
    public var type: AncestorType?

    public init(_id: String? = nil, type: AncestorType? = nil) {
        self._id = _id
        self.type = type
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case type
    }

}
