//
// Ancestor.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Ancestor {

    /** ID of the ancestor */
    public var id: String?
    public var type: AncestorType?

    public init(id: String? = nil, type: AncestorType? = nil) {
        self.id = id
        self.type = type
    }

    public enum CodingKeys: String, CodingKey { 
        case id = "id"
        case type
    }

}
