//
// AncestorType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The type of ancestor. */
public enum AncestorType: String, Codable {
    case page = "page"
    case whiteboard = "whiteboard"
    case database = "database"
    case embed = "embed"
    case folder = "folder"
}