//
// AttachmentLinks.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AttachmentLinks: Codable {

    /** Web UI link of the content. */
    public var webui: String?
    /** Download link of the content. */
    public var download: String?

    public init(webui: String? = nil, download: String? = nil) {
        self.webui = webui
        self.download = download
    }


}
