//
// AttachmentCommentModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AttachmentCommentModel: Codable {

    /** ID of the comment. */
    public var _id: String?
    public var status: ContentStatus?
    /** Title of the comment. */
    public var title: String?
    /** ID of the attachment containing the comment. */
    public var attachmentId: String?
    public var version: Version?
    public var body: BodySingle?
    public var links: CommentLinks?

    public init(_id: String? = nil, status: ContentStatus? = nil, title: String? = nil, attachmentId: String? = nil, version: Version? = nil, body: BodySingle? = nil, links: CommentLinks? = nil) {
        self._id = _id
        self.status = status
        self.title = title
        self.attachmentId = attachmentId
        self.version = version
        self.body = body
        self.links = links
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case status
        case title
        case attachmentId
        case version
        case body
        case links = "_links"
    }

}
