//
// BlogPostContentStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The status of the content. */
public enum BlogPostContentStatus: String, Codable {
    case current = "current"
    case draft = "draft"
    case historical = "historical"
    case trashed = "trashed"
    case deleted = "deleted"
    case any = "any"
}