//
// BlogPostBulk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BlogPostBulk {

    /** ID of the blog post. */
    public var id: String?
    public var status: BlogPostContentStatus?
    /** Title of the blog post. */
    public var title: String?
    /** ID of the space the blog post is in. */
    public var spaceId: String?
    /** The account ID of the user who created this blog post originally. */
    public var authorId: String?
    /** Date and time when the blog post was created. In format \&quot;YYYY-MM-DDTHH:mm:ss.sssZ\&quot;. */
    public var createdAt: Date?
    public var version: Version?
    public var body: BodyBulk?
    public var links: AbstractPageLinks?

    public init(id: String? = nil, status: BlogPostContentStatus? = nil, title: String? = nil, spaceId: String? = nil, authorId: String? = nil, createdAt: Date? = nil, version: Version? = nil, body: BodyBulk? = nil, links: AbstractPageLinks? = nil) {
        self.id = id
        self.status = status
        self.title = title
        self.spaceId = spaceId
        self.authorId = authorId
        self.createdAt = createdAt
        self.version = version
        self.body = body
        self.links = links
    }

    public enum CodingKeys: String, CodingKey { 
        case id = "id"
        case status
        case title
        case spaceId
        case authorId
        case createdAt
        case version
        case body
        case links = "links"
    }

}
