//
// BlogPostNestedBodyWrite.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Body of the blog post. Only one body format should be specified as the property for this object, e.g. &#x60;storage&#x60;. */

public struct BlogPostNestedBodyWrite {

    public var storage: BlogPostBodyWrite?
    public var atlasDocFormat: BlogPostBodyWrite?
    public var wiki: BlogPostBodyWrite?

    public init(storage: BlogPostBodyWrite? = nil, atlasDocFormat: BlogPostBodyWrite? = nil, wiki: BlogPostBodyWrite? = nil) {
        self.storage = storage
        self.atlasDocFormat = atlasDocFormat
        self.wiki = wiki
    }

    public enum CodingKeys: String, CodingKey { 
        case storage
        case atlasDocFormat = "atlasdocformat"
        case wiki
    }

}
