//
// BlogPostCommentModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BlogPostCommentModel {

    /** ID of the comment. */
    public var id: String?
    public var status: ContentStatus?
    /** Title of the comment. */
    public var title: String?
    /** ID of the blog post the comment is in. */
    public var blogPostId: String?
    public var version: Version?
    public var body: BodyBulk?
    public var links: CommentLinks?

    public init(id: String? = nil, status: ContentStatus? = nil, title: String? = nil, blogPostId: String? = nil, version: Version? = nil, body: BodyBulk? = nil, links: CommentLinks? = nil) {
        self.id = id
        self.status = status
        self.title = title
        self.blogPostId = blogPostId
        self.version = version
        self.body = body
        self.links = links
    }

    public enum CodingKeys: String, CodingKey { 
        case id = "id"
        case status
        case title
        case blogPostId
        case version
        case body
        case links = "links"
    }

}
