//
// ChildCustomContent.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChildCustomContent {

    /** ID of the child custom content. */
    public var id: String?
    public var status: OnlyArchivedAndCurrentContentStatus?
    /** Title of the custom content. */
    public var title: String?
    /** Custom content type. */
    public var type: String?
    /** ID of the space the custom content is in. */
    public var spaceId: String?

}
