//
// ChildPageSortOrder.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The sort fields for child pages. The default sort direction is ascending by child-position. To sort in descending order, append a &#x60;-&#x60; character before the sort field. For example, &#x60;fieldName&#x60; or &#x60;-fieldName&#x60;. */
public enum ChildPageSortOrder: String {
    case createdDate = "created-date"
    case _id = "id"
    case childPosition = "child-position"
    case modifiedDate = "modified-date"
}
