//
// ClassificationLevelColor.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum ClassificationLevelColor: String, Codable {
    case red = "RED"
    case redBold = "RED_BOLD"
    case orange = "ORANGE"
    case yellow = "YELLOW"
    case green = "GREEN"
    case blue = "BLUE"
    case navy = "NAVY"
    case teal = "TEAL"
    case purple = "PURPLE"
    case grey = "GREY"
    case lime = "LIME"
}