//
// CommentNestedBodyWrite.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Body of the comment. Only one body format should be specified as the property for this object, e.g. &#x60;storage&#x60;. */

public struct CommentNestedBodyWrite {

    public var storage: CommentBodyWrite?
    public var atlasDocFormat: CommentBodyWrite?
    public var wiki: CommentBodyWrite?

    public init(storage: CommentBodyWrite? = nil, atlasDocFormat: CommentBodyWrite? = nil, wiki: CommentBodyWrite? = nil) {
        self.storage = storage
        self.atlasDocFormat = atlasDocFormat
        self.wiki = wiki
    }

    public enum CodingKeys: String, CodingKey { 
        case storage
        case atlasDocFormat = "atlasdocformat"
        case wiki
    }

}
