//
// ContentIdToContentTypeResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ContentIdToContentTypeResponse {

    /** JSON object containing all requested content ids as keys and their associated content types as the values. Duplicate content ids in the request will be returned under a single key in the response. For built-in content types, the enumerations are as specified. Custom content ids will be mapped to their associated type. */
    public var results: [String:Any]?

    public init(results: [String:Any]? = nil) {
        self.results = results
    }


}
