//
// ContentPropertyUpdateRequestVersion.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** New version number and associated message */

public struct ContentPropertyUpdateRequestVersion {

    /** Version number of the new version. Should be 1 more than the current version number. */
    public var number: Int?
    /** Message to be associated with the new version. */
    public var message: String?

    public init(number: Int? = nil, message: String? = nil) {
        self.number = number
        self.message = message
    }


}
