//
// ContentPropertyCreateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ContentPropertyCreateRequest {

    /** Key of the content property */
    public var key: String?
    /** Value of the content property. */
    public var value: Any?

    public init(key: String? = nil, value: Any? = nil) {
        self.key = key
        self.value = value
    }


}
