//
// ContentPropertyUpdateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ContentPropertyUpdateRequest {

    /** Key of the content property */
    public var key: String?
    /** Value of the content property. */
    public var value: Any?
    public var version: ContentPropertyUpdateRequestVersion?

    public init(key: String? = nil, value: Any? = nil, version: ContentPropertyUpdateRequestVersion? = nil) {
        self.key = key
        self.value = value
        self.version = version
    }


}
