//
// CreateInlineCommentModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreateInlineCommentModel {

    /** ID of the containing blog post, if intending to create a top level footer comment. Do not provide if creating a reply. */
    public var blogPostId: String?
    /** ID of the containing page, if intending to create a top level footer comment. Do not provide if creating a reply. */
    public var pageId: String?
    /** ID of the parent comment, if intending to create a reply. Do not provide if creating a top level comment. */
    public var parentCommentId: String?
    public var body: OneOfCreateInlineCommentModelBody?
    public var inlineCommentProperties: CreateInlineCommentModelInlineCommentProperties?

    public init(blogPostId: String? = nil, pageId: String? = nil, parentCommentId: String? = nil, body: OneOfCreateInlineCommentModelBody? = nil, inlineCommentProperties: CreateInlineCommentModelInlineCommentProperties? = nil) {
        self.blogPostId = blogPostId
        self.pageId = pageId
        self.parentCommentId = parentCommentId
        self.body = body
        self.inlineCommentProperties = inlineCommentProperties
    }


}
