//
// CreateFooterCommentModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreateFooterCommentModel: Codable {

    /** ID of the containing blog post, if intending to create a top level footer comment. Do not provide if creating a reply. */
    public var blogPostId: String?
    /** ID of the containing page, if intending to create a top level footer comment. Do not provide if creating a reply. */
    public var pageId: String?
    /** ID of the parent comment, if intending to create a reply. Do not provide if creating a top level comment. */
    public var parentCommentId: String?
    /** ID of the attachment, if intending to create a comment against an attachment. */
    public var attachmentId: String?
    /** ID of the custom content, if intending to create a comment against a custom content. */
    public var customContentId: String?
    public var body: OneOfCreateFooterCommentModelBody?

    public init(blogPostId: String? = nil, pageId: String? = nil, parentCommentId: String? = nil, attachmentId: String? = nil, customContentId: String? = nil, body: OneOfCreateFooterCommentModelBody? = nil) {
        self.blogPostId = blogPostId
        self.pageId = pageId
        self.parentCommentId = parentCommentId
        self.attachmentId = attachmentId
        self.customContentId = customContentId
        self.body = body
    }


}
