//
// CustomContentBodyRepresentationSingle.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The formats a custom content body can be represented as. A subset of BodyRepresentation. */
public enum CustomContentBodyRepresentationSingle: String, Codable {
    case raw = "raw"
    case storage = "storage"
    case atlasDocFormat = "atlasdocformat"
    case view = "view"
    case exportView = "exportview"
    case anonymousExportView = "anonymousexportview"
}