//
// CustomContentNestedBodyWrite.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Body of the custom content. Only one body format should be specified as the property for this object, e.g. &#x60;storage&#x60;. */

public struct CustomContentNestedBodyWrite: Codable {

    public var storage: CustomContentBodyWrite?
    public var atlasDocFormat: CustomContentBodyWrite?
    public var raw: CustomContentBodyWrite?

    public init(storage: CustomContentBodyWrite? = nil, atlasDocFormat: CustomContentBodyWrite? = nil, raw: CustomContentBodyWrite? = nil) {
        self.storage = storage
        self.atlasDocFormat = atlasDocFormat
        self.raw = raw
    }

    public enum CodingKeys: String, CodingKey { 
        case storage
        case atlasDocFormat = "atlas_doc_format"
        case raw
    }

}
