//
// CustomContentBulk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CustomContentBulk: Codable {

    /** ID of the custom content. */
    public var _id: String?
    /** The type of custom content. */
    public var type: String?
    public var status: ContentStatus?
    /** Title of the custom content. */
    public var title: String?
    /** ID of the space the custom content is in.  Note: This is always returned, regardless of if the custom content has a container that is a space. */
    public var spaceId: String?
    /** ID of the containing page.  Note: This is only returned if the custom content has a container that is a page. */
    public var pageId: String?
    /** ID of the containing blog post.  Note: This is only returned if the custom content has a container that is a blog post. */
    public var blogPostId: String?
    /** ID of the containing custom content.  Note: This is only returned if the custom content has a container that is custom content. */
    public var customContentId: String?
    /** The account ID of the user who created this custom content originally. */
    public var authorId: String?
    /** Date and time when the custom content was created. In format \&quot;YYYY-MM-DDTHH:mm:ss.sssZ\&quot;. */
    public var createdAt: Date?
    public var version: Version?
    public var body: CustomContentBodyBulk?
    public var links: CustomContentLinks?

    public init(_id: String? = nil, type: String? = nil, status: ContentStatus? = nil, title: String? = nil, spaceId: String? = nil, pageId: String? = nil, blogPostId: String? = nil, customContentId: String? = nil, authorId: String? = nil, createdAt: Date? = nil, version: Version? = nil, body: CustomContentBodyBulk? = nil, links: CustomContentLinks? = nil) {
        self._id = _id
        self.type = type
        self.status = status
        self.title = title
        self.spaceId = spaceId
        self.pageId = pageId
        self.blogPostId = blogPostId
        self.customContentId = customContentId
        self.authorId = authorId
        self.createdAt = createdAt
        self.version = version
        self.body = body
        self.links = links
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case type
        case status
        case title
        case spaceId
        case pageId
        case blogPostId
        case customContentId
        case authorId
        case createdAt
        case version
        case body
        case links = "_links"
    }

}
