//
// DataPolicySpaceDataPolicy.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DataPolicySpaceDataPolicy {

    /** Whether the space contains any content blocked for (inaccessible to) the requesting client application. */
    public var anyContentBlocked: Bool?

    public init(anyContentBlocked: Bool? = nil) {
        self.anyContentBlocked = anyContentBlocked
    }


}
