//
// DataPolicySpace.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DataPolicySpace {

    /** ID of the space. */
    public var id: String?
    /** Key of the space. */
    public var key: String?
    /** Name of the space. */
    public var name: String?
    public var description: SpaceDescription?
    public var dataPolicy: DataPolicySpaceDataPolicy?
    public var icon: SpaceIcon?
    public var links: SpaceLinks?

    public init(id: String? = nil, key: String? = nil, name: String? = nil, description: SpaceDescription? = nil, dataPolicy: DataPolicySpaceDataPolicy? = nil, icon: SpaceIcon? = nil, links: SpaceLinks? = nil) {
        self.id = id
        self.key = key
        self.name = name
        self.description = description
        self.dataPolicy = dataPolicy
        self.icon = icon
        self.links = links
    }

}
