//
// DatabaseLinks.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DatabaseLinks {

    /** Web UI link of the content. */
    public var webui: String?

    public init(webui: String? = nil) {
        self.webui = webui
    }


}
