//
// FootercommentsCommentidBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FootercommentsCommentidBody {

    public var links: FootercommentscommentidLinks?
    public var version: UpdateFooterCommentModelVersion?
    public var body: Any?

}
