//
// FootercommentscommentidLinks.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FootercommentscommentidLinks: Codable {

    /** Base url of the Confluence site. */
    public var base: String?

    public init(base: String? = nil) {
        self.base = base
    }


}
