//
// FooterCommentModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FooterCommentModel {

    /** ID of the comment. */
    public var _id: String?
    public var status: ContentStatus?
    /** Title of the comment. */
    public var title: String?
    /** ID of the blog post containing the comment if the comment is on a blog post. */
    public var blogPostId: String?
    /** ID of the page containing the comment if the comment is on a page. */
    public var pageId: String?
    /** ID of the attachment containing the comment if the comment is on an attachment. */
    public var attachmentId: String?
    /** ID of the custom content containing the comment if the comment is on a custom content. */
    public var customContentId: String?
    /** ID of the parent comment if the comment is a reply. */
    public var parentCommentId: String?
    public var version: Version?
    public var properties: AttachmentSingleProperties?
    public var operations: AttachmentSingleOperations?
    public var likes: BlogPostSingleLikes?
    public var versions: AttachmentSingleVersions?
    public var body: BodySingle?
    public var links: CommentLinks?

}
