//
// InlineResponse2002.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse2002 {

    public var links: FootercommentscommentidLinks?
    /** ID of the page. */
    public var _id: String?
    public var status: ContentStatus?
    /** Title of the page. */
    public var title: String?
    /** ID of the space the page is in. */
    public var spaceId: String?
    /** ID of the parent page, or null if there is no parent page. */
    public var parentId: String?
    public var parentType: ParentContentType?
    /** Position of child page within the given parent page tree. */
    public var position: Int?
    /** The account ID of the user who created this page originally. */
    public var authorId: String?
    /** The account ID of the user who owns this page. */
    public var ownerId: String?
    /** The account ID of the user who owned this page previously, or null if there is no previous owner. */
    public var lastOwnerId: String?
    /** Date and time when the page was created. In format \&quot;YYYY-MM-DDTHH:mm:ss.sssZ\&quot;. */
    public var createdAt: Date?
    public var version: Version?
    public var body: BodySingle?
    public var labels: AttachmentSingleLabels?
    public var properties: AttachmentSingleProperties?
    public var operations: AttachmentSingleOperations?
    public var likes: BlogPostSingleLikes?
    public var versions: AttachmentSingleVersions?
    /** Whether the page has been favorited by the current user. */
    public var isFavoritedByCurrentUser: Bool?

}
