//
// InlineCommentResolutionStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Inline comment resolution status */
public enum InlineCommentResolutionStatus: String, Codable {
    case open = "open"
    case reopened = "reopened"
    case resolved = "resolved"
    case dangling = "dangling"
}