//
// InlineResponse2008.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse2008 {

    /** List of emails that do not have access to site. */
    public var emailsWithoutAccess: [String]?
    /** List of invalid emails provided in the request. */
    public var invalidEmails: [String]?

    public init(emailsWithoutAccess: [String]? = nil, invalidEmails: [String]? = nil) {
        self.emailsWithoutAccess = emailsWithoutAccess
        self.invalidEmails = invalidEmails
    }


}
