//
// Integer.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Integer: Codable {

    /** The count number */
    public var count: Int64?

    public init(count: Int64? = nil) {
        self.count = count
    }


}
