//
// LabelSortOrder.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The sort fields for labels. The default sort direction is ascending. To sort in descending order, append a &#x60;-&#x60; character before the sort field. For example, &#x60;fieldName&#x60; or &#x60;-fieldName&#x60;. */
public enum LabelSortOrder: String {
    case createdDate = "created-date"
    case id = "id"
    case name = "name"
}
