//
// MultiEntityResultFooterCommentModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MultiEntityResultFooterCommentModel {

    public var results: [FooterCommentModel]?
    public var links: MultiEntityLinks?

    public init(results: [FooterCommentModel]? = nil, links: MultiEntityLinks? = nil) {
        self.results = results
        self.links = links
    }

}
