//
// MultiEntityResultPageCommentModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MultiEntityResultPageCommentModel {

    public var results: [PageCommentModel]?
    public var links: MultiEntityLinks?

    public init(results: [PageCommentModel]? = nil, links: MultiEntityLinks? = nil) {
        self.results = results
        self.links = links
    }

}
