//
// MultiEntityResultString.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MultiEntityResultString {

    public var results: [Like]?
    public var links: MultiEntityLinks?

    public init(results: [Like]? = nil, links: MultiEntityLinks? = nil) {
        self.results = results
        self.links = links
    }

}
