//
// MultiEntityLinks.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MultiEntityLinks {

    /** Used for pagination. Contains the relative URL for the next set of results, using a cursor query parameter. This property will not be present if there is no additional data available. */
    public var next: String?
    /** Base url of the Confluence site. */
    public var base: String?

    public init(next: String? = nil, base: String? = nil) {
        self.next = next
        self.base = base
    }


}
