//
// MultiEntityResultSpaceProperty.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MultiEntityResultSpaceProperty {

    public var results: [SpaceProperty]?
    public var links: MultiEntityLinks?

    public init(results: [SpaceProperty]? = nil, links: MultiEntityLinks? = nil) {
        self.results = results
        self.links = links
    }

}
