//
// MultiEntityResultAncestor.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MultiEntityResultAncestor: Codable {

    public var results: [Ancestor]?

    public init(results: [Ancestor]? = nil) {
        self.results = results
    }


}
