//
// MultiEntityResultChildCustomContent.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MultiEntityResultChildCustomContent {

    public var results: [ChildCustomContent]?
    public var links: MultiEntityLinks?

    public init(results: [ChildCustomContent]? = nil, links: MultiEntityLinks? = nil) {
        self.results = results
        self.links = links
    }

}
