//
// MultiEntityResultInlineCommentChildrenModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MultiEntityResultInlineCommentChildrenModel {

    public var results: [InlineCommentChildrenModel]?
    public var links: MultiEntityLinks?

    public init(results: [InlineCommentChildrenModel]? = nil, links: MultiEntityLinks? = nil) {
        self.results = results
        self.links = links
    }

}
