//
// MultiEntityResultSpace.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MultiEntityResultSpace {

    public var results: [SpaceBulk]?
    public var links: MultiEntityLinks?

    public init(results: [SpaceBulk]? = nil, links: MultiEntityLinks? = nil) {
        self.results = results
        self.links = links
    }

}
