//
// MultiEntityResultPageInlineCommentModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MultiEntityResultPageInlineCommentModel {

    public var results: [PageInlineCommentModel]?
    public var links: MultiEntityLinks?

    public init(results: [PageInlineCommentModel]? = nil, links: MultiEntityLinks? = nil) {
        self.results = results
        self.links = links
    }

}
