//
// MultiEntityResultVersion3.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MultiEntityResultVersion3 {

    public var results: [CustomContentVersion]?
    public var links: MultiEntityLinks?

    public init(results: [CustomContentVersion]? = nil, links: MultiEntityLinks? = nil) {
        self.results = results
        self.links = links
    }

}
