//
// MultiEntityResultVersion2.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MultiEntityResultVersion2 {

    public var results: [PageVersion]?
    public var links: MultiEntityLinks?

    public init(results: [PageVersion]? = nil, links: MultiEntityLinks? = nil) {
        self.results = results
        self.links = links
    }

}
