//
// PageCommentModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PageCommentModel {

    /** ID of the comment. */
    public var id: String?
    public var status: ContentStatus?
    /** Title of the comment. */
    public var title: String?
    /** ID of the page the comment is in. */
    public var pageId: String?
    public var version: Version?
    public var body: BodyBulk?
    public var links: CommentLinks?

    public init(id: String? = nil, status: ContentStatus? = nil, title: String? = nil, pageId: String? = nil, version: Version? = nil, body: BodyBulk? = nil, links: CommentLinks? = nil) {
        self.id = id
        self.status = status
        self.title = title
        self.pageId = pageId
        self.version = version
        self.body = body
        self.links = links
    }

}
