//
// PageNestedBodyWrite.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Body of the page. Only one body format should be specified as the property for this object, e.g. &#x60;storage&#x60;. */

public struct PageNestedBodyWrite {

    public var storage: PageBodyWrite?
    public var atlasDocFormat: PageBodyWrite?
    public var wiki: PageBodyWrite?

    public init(storage: PageBodyWrite? = nil, atlasDocFormat: PageBodyWrite? = nil, wiki: PageBodyWrite? = nil) {
        self.storage = storage
        self.atlasDocFormat = atlasDocFormat
        self.wiki = wiki
    }

}
