//
// PageBodyWrite.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PageBodyWrite {

    public enum Representation: String, Codable { 
        case storage = "storage"
        case atlasDocFormat = "atlasdocformat"
        case wiki = "wiki"
    }
    /** Type of content representation used for the value field. */
    public var representation: Representation?
    /** Body of the page, in the format found in the representation field. */
    public var value: String?

    public init(representation: Representation? = nil, value: String? = nil) {
        self.representation = representation
        self.value = value
    }


}
