//
// PermittedOperationsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The list of operations permitted on entity. */

public struct PermittedOperationsResponse {

    public var operations: [Operation]?

    public init(operations: [Operation]? = nil) {
        self.operations = operations
    }


}
