//
// PrimaryBodyRepresentationSingle.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The primary formats a body can be represented as. A subset of BodyRepresentation. These formats are the only allowed formats in certain use cases. */
public enum PrimaryBodyRepresentationSingle: String, Codable {
    case storage = "storage"
    case atlasDocFormat = "atlasdocformat"
    case view = "view"
    case exportView = "exportview"
    case anonymousExportView = "anonymousexportview"
    case styledView = "styledview"
    case editor = "editor"
}