//
// SpaceStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The status of the space. */
public enum SpaceStatus: String, Codable {
    case current = "current"
    case archived = "archived"
}