//
// SpaceType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The type of space. */
public enum SpaceType: String, Codable {
    case global = "global"
    case collaboration = "collaboration"
    case knowledgeBase = "knowledgebase"
    case personal = "personal"
}