//
// SpacePermission.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SpacePermission: Codable {

    /** ID of the space permission. */
    public var _id: String?
    public var principal: SpacePermissionPrincipal?
    public var operation: SpacePermissionOperation?

    public init(_id: String? = nil, principal: SpacePermissionPrincipal? = nil, operation: SpacePermissionOperation? = nil) {
        self._id = _id
        self.principal = principal
        self.operation = operation
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case principal
        case operation
    }

}
