//
// SpacePropertyCreateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SpacePropertyCreateRequest {

    /** Key of the space property */
    public var key: String?
    /** Value of the space property. */
    public var value: Any?

    public init(key: String? = nil, value: Any? = nil) {
        self.key = key
        self.value = value
    }


}
