//
// SpaceLinks.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SpaceLinks: Codable {

    /** Web UI link of the space. */
    public var webui: String?

    public init(webui: String? = nil) {
        self.webui = webui
    }


}
