//
// SpaceDescription.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Contains fields for each representation type requested. */

public struct SpaceDescription: Codable {

    public var plain: BodyType?
    public var view: BodyType?

    public init(plain: BodyType? = nil, view: BodyType? = nil) {
        self.plain = plain
        self.view = view
    }


}
