//
// SpaceSortOrder.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The sort fields for spaces. The default sort direction is ascending. To sort in descending order, append a &#x60;-&#x60; character before the sort field. For example, &#x60;fieldName&#x60; or &#x60;-fieldName&#x60;. */
public enum SpaceSortOrder: String, Codable {
    case id = "id"
    case key = "key"
    case name = "name"
}
