//
// SpaceBulk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SpaceBulk: Codable {

    /** ID of the space. */
    public var _id: String?
    /** Key of the space. */
    public var key: String?
    /** Name of the space. */
    public var name: String?
    public var type: SpaceType?
    public var status: SpaceStatus?
    /** The account ID of the user who created this space originally. */
    public var authorId: String?
    /** Date and time when the space was created. In format \&quot;YYYY-MM-DDTHH:mm:ss.sssZ\&quot;. */
    public var createdAt: Date?
    /** ID of the space&#x27;s homepage. */
    public var homepageId: String?
    public var _description: SpaceDescription?
    public var icon: SpaceIcon?
    public var links: SpaceLinks?

    public init(_id: String? = nil, key: String? = nil, name: String? = nil, type: SpaceType? = nil, status: SpaceStatus? = nil, authorId: String? = nil, createdAt: Date? = nil, homepageId: String? = nil, _description: SpaceDescription? = nil, icon: SpaceIcon? = nil, links: SpaceLinks? = nil) {
        self._id = _id
        self.key = key
        self.name = name
        self.type = type
        self.status = status
        self.authorId = authorId
        self.createdAt = createdAt
        self.homepageId = homepageId
        self._description = _description
        self.icon = icon
        self.links = links
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case key
        case name
        case type
        case status
        case authorId
        case createdAt
        case homepageId
        case _description = "description"
        case icon
        case links = "_links"
    }

}
