//
// SpacePermission.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SpacePermission {

    /** ID of the space permission. */
    public var id: String?
    public var principal: SpacePermissionPrincipal?
    public var operation: SpacePermissionOperation?

    public init(id: String? = nil, principal: SpacePermissionPrincipal? = nil, operation: SpacePermissionOperation? = nil) {
        self.id = id
        self.principal = principal
        self.operation = operation
    }

}
