//
// SpaceProperty.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SpaceProperty {

    /** ID of the space property. */
    public var id: String?
    /** Key of the space property. */
    public var key: String?
    /** Value of the space property. */
    public var value: Any?
    /** RFC3339 compliant date time at which the property was created. */
    public var createdAt: Date?
    /** Atlassian account ID of the user that created the space property. */
    public var createdBy: String?
    public var version: SpacePropertyVersion?

    public init(id: String? = nil, key: String? = nil, value: Any? = nil, createdAt: Date? = nil, createdBy: String? = nil, version: SpacePropertyVersion? = nil) {
        self.id = id
        self.key = key
        self.value = value
        self.createdAt = createdAt
        self.createdBy = createdBy
        self.version = version
    }

}
