//
// SpaceDescriptionBodyRepresentation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The formats a space description can be represented as. A subset of BodyRepresentation. */
public enum SpaceDescriptionBodyRepresentation: String, Codable {
    case plain = "plain"
    case view = "view"
}