//
// SpacePermissionOperation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The operation the space permission corresponds to. */

public struct SpacePermissionOperation {

    public enum Key: String, Codable { 
        case use = "use"
        case create = "create"
        case read = "read"
        case update = "update"
        case delete = "delete"
        case copy = "copy"
        case move = "move"
        case export = "export"
        case purge = "purge"
        case purgeVersion = "purgeversion"
        case administer = "administer"
        case restore = "restore"
        case createSpace = "createspace"
        case restrictContent = "restrictcontent"
        case archive = "archive"
    }
    public enum TargetType: String, Codable { 
        case page = "page"
        case blogpost = "blogpost"
        case comment = "comment"
        case attachment = "attachment"
        case whiteboard = "whiteboard"
        case database = "database"
        case embed = "embed"
        case folder = "folder"
        case space = "space"
        case application = "application"
        case userprofile = "userProfile"
    }
    /** The type of operation. */
    public var key: Key?
    /** The type of entity the operation type targets. */
    public var targetType: TargetType?

    public init(key: Key? = nil, targetType: TargetType? = nil) {
        self.key = key
        self.targetType = targetType
    }


}
