//
// TaskBodySingle.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Contains fields for each representation type requested. */

public struct TaskBodySingle {

    public var storage: BodyType?
    public var atlasDocFormat: BodyType?

    public init(storage: BodyType? = nil, atlasDocFormat: BodyType? = nil) {
        self.storage = storage
        self.atlasDocFormat = atlasDocFormat
    }

}
