//
// UpdateFooterCommentModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UpdateFooterCommentModel {

    public var version: UpdateFooterCommentModelVersion?
    public var body: OneOfUpdateFooterCommentModelBody?

    public init(version: UpdateFooterCommentModelVersion? = nil, body: OneOfUpdateFooterCommentModelBody? = nil) {
        self.version = version
        self.body = body
    }


}
