//
// UpdateFooterCommentModelVersion.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UpdateFooterCommentModelVersion: Codable {

    /** Number of new version. Should be 1 higher than current version of the comment. */
    public var number: Int?
    /** Optional message store for the new version. */
    public var message: String?

    public init(number: Int? = nil, message: String? = nil) {
        self.number = number
        self.message = message
    }


}
