//
// VersionedEntity.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VersionedEntity: Codable {

    /** Title of the entity. */
    public var title: String?
    /** ID of the entity. */
    public var _id: String?
    public var body: BodyBulk?

    public init(title: String? = nil, _id: String? = nil, body: BodyBulk? = nil) {
        self.title = title
        self._id = _id
        self.body = body
    }

    public enum CodingKeys: String, CodingKey { 
        case title
        case _id = "id"
        case body
    }

}
