//
// VersionedEntity.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VersionedEntity {

    /** Title of the entity. */
    public var title: String?
    /** ID of the entity. */
    public var id: String?
    public var body: BodyBulk?

    public init(title: String? = nil, id: String? = nil, body: BodyBulk? = nil) {
        self.title = title
        self.id = id
        self.body = body
    }

}
