//
// WhiteboardLinks.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct WhiteboardLinks: Codable {

    /** Web UI link of the content. */
    public var webui: String?
    /** Edit UI link of the content. */
    public var editui: String?

    public init(webui: String? = nil, editui: String? = nil) {
        self.webui = webui
        self.editui = editui
    }


}
